version: '3.9'
services: 
  db:
      image: "mcr.microsoft.com/mssql/server"
      volumes:
        - ./db_data:/var/opt/mssql/data
      ports:
        - 1435:1435
      environment: 
        SA_PASSWORD: 'Nazarinebeats0!'
        ACCEPT_EULA: 'Y'